apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: data-console-demo-test-1
  namespace: workspace-8
  labels:
    docs.crossplane.io/example: provider-gcp
spec:
  forProvider:
    location: US
  providerConfigRef:
    name: default